#!/bin/bash
#SBATCH --job-name=DMT
#SBATCH --mail-type=fail
#SBATCH --output ./DMT_%J.out
#SBATCH --chdir=./
#SBATCH --ntasks=1
#SBATCH --account=m4324
#SBATCH --constraint=cpu
#SBATCH --qos=shared
######SBATCH --qos=regular
#######SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --mem=64GB
#SBATCH --time=8:00:00
#######SBATCH --time=00:30:00

## Run command
module load DMT_perlmutter
export PYTHONPATH="${PYTHONPATH}:/home/sajant/Research/Berkeley/QEC/BP-Loop-Decoding/codes/"
export PYTHONPATH="${PYTHONPATH}:/home/sajant/Research/Berkeley/QEC/pyfssa/"
echo $PYTHONPATH

current_time=$(date +%s)
echo "Current time: $current_time"

python3 k_surface_code_BP.py \
    `#nc:`          2    \
    `#L_str:`       5-9   \
    `#k_str:`       1    \
    `#num_shots:`   50000  \
    `#BP_method:`   product_sum \
    `#max_iter:`    30 \
    `#schedule:`    serial \
    `#OSD:`	    0 \
    `#OSD_method:`  OSD_0 \
    `#OSD_order:`   0 \
    `#seed:`        -1 
